@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@userId = da0dd04b-76dc-4520-b3e7-318b039f3a2

###

GET http://{{host}}/users

###

GET http://{{host}}/users/{{userId}}

###

POST http://{{host}}/users
content-type: {{contentType}}

{
  "email": "jeanpi3rm@gmail.com",
  "age": 22
}

###

PATCH http://{{host}}/users/{{userId}}
content-type: {{contentType}}

{
  "favoriteFoods": ["huevos", "leche"]
}